baseURL = "https://halimboi.com/"
languageCode = "id-ID"
DefaultContentLanguage = "id"
title = "halimboi.com"
theme = "less"
timeout = 200000
RemovePathAccents = true
enableRobotsTXT = true
canonifyURLs = true
paginate = 5
googleAnalytics = "UA-155099144-3"
disqusShortname = "halimboi"

[author]
  name = "Doni Halim"

[blackfriday]
  hrefTargetBlank = true
  noreferrerLinks = true
  nofollowLinks = true

[permalinks]
  posts = "/:slug"
  categories = "/:slug"

[imaging]
  resampleFilter = "lanczos"

[params]
  #googleAdsense = "ca-pub-3520097993586116"
  copyright = "Halimboi"

  # image size
  sizes = [ "2048" , "1024" , "512" ]
  tags = []

  # fonts
  sansSerifFont = "Josefin Sans"
  titleFont = "Crimson Text"
  bodyFont = "Lora"

  # color
  accentColor = "#00bcd4"
  hasLogo = true
  heroHeader = true

[taxonomies]
  category = "categories"

[params.titles]
  posts = "Linux"
  categories = "Kategori"

# social
[params.social]
  email = "donihalim@protonmail.com"
  domain = "Doni Halim"
  instagram = "dsnvhlmb"
  twitter = "halimboi"
  facebook = "drtunicorn"
  linkedin = "doni-halim-16a6ba1a0"
  github = "donihalim"
  paypal = "halimboi"
  telegram = "dsnvhlm"

# menu contents
[[menu.main]]
  name = "Perkakas"
  title = "Perkakas GNU/Linux"
  weight = 1
  identifier = "perkakas"
  url = "/perkakas"
[[menu.main]]
  name = "Terminal"
  title = "Perintah-perintah dasar dan lanjutan GNU/Linux"
  weight = 2
  identifier = "terminal"
  url = "/terminal"
[[menu.main]]
  name = "Desktop"
  title = "Kostumisasi lingkungan desktop GNU/Linux"
  weight = 3
  identifier = "desktop"
  url = "/desktop"
[[menu.main]]
  name = "Profil"
  title = "Tentang Doni Halim"
  weight = 4
  identifier = "profil"
  url = "/profil"

# footer contents
[params.license]
  type = "CC BY-NC 4.0"
  url = "/cc-by-nc"

[params.policy]
  type = "Privacy Policy"
  url = "/policy"

[[related.indices]]
  name = "categories"
  weight =  1
  includeNewer = true
